import os
from datetime import datetime
from typing import List, Set


class SitemapBuilder:
    def __init__(self, base_url: str = "https://lianglu.uk", root_path: str = "."):
        self.base_url = base_url.rstrip('/')
        self.root_path = root_path
        self.urls: Set[str] = set()

    def scan_html_files(self):
        """掃描專案中的所有 HTML 檔案並提取路徑"""
        # 要掃描的目錄
        directories = [
            ".",
            "projects",
            "awards",
            "knowledge",
            "jobs",
            "skills"
        ]

        for directory in directories:
            dir_path = os.path.join(self.root_path, directory)
            if not os.path.exists(dir_path):
                continue

            for file in os.listdir(dir_path):
                # 排除測試檔案和 Google 驗證檔案
                if file.endswith('.html') and file != 'test.html' and not file.startswith('google'):
                    # 移除 .html 擴展名
                    file_without_ext = file.replace('.html', '')

                    # 根據目錄構建 URL
                    if directory == ".":
                        if file == "index.html":
                            url = "/"
                        else:
                            url = f"/{file_without_ext}"
                    else:
                        if file == "index.html":
                            url = f"/{directory}"
                        else:
                            url = f"/{directory}/{file_without_ext}"

                    self.urls.add(url)

    def generate_sitemap(self) -> str:
        """生成 sitemap XML 內容"""
        # 當前時間
        now = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S+00:00')

        # 開始構建 XML
        xml_lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<urlset',
            '      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
            '      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
            '      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9',
            '            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">',
            '<!-- Auto-generated by Personal-OfficialWeb builder -->',
            ''
        ]

        # 排序 URL 列表，首頁優先
        sorted_urls = sorted(self.urls, key=lambda x: (x != '/', x))

        # 為每個 URL 生成條目
        for url in sorted_urls:
            # 設定優先級：首頁 1.00，其他頁面 0.80
            priority = "1.00" if url == "/" else "0.80"

            full_url = f"{self.base_url}{url}" if url != "/" else f"{self.base_url}/"

            xml_lines.extend([
                '<url>',
                f'  <loc>{full_url}</loc>',
                f'  <lastmod>{now}</lastmod>',
                f'  <priority>{priority}</priority>',
                '</url>'
            ])

        xml_lines.extend([
            '',
            '</urlset>'
        ])

        return '\n'.join(xml_lines)

    def build(self, output_file: str = "sitemap.xml"):
        """建立並儲存 sitemap"""
        # 掃描所有 HTML 檔案
        self.scan_html_files()

        # 生成 sitemap 內容
        sitemap_content = self.generate_sitemap()

        # 寫入檔案
        output_path = os.path.join(self.root_path, output_file)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(sitemap_content)

        print(f"Sitemap generated successfully. File: {output_path}")
        print(f"Total URLs: {len(self.urls)}")


# 建立全域實例
sitemapBuilder = SitemapBuilder()
